config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "pages#home"
  resources :flats do
    resources :bookings, only: [:index, :show, :create] do
      member do
        patch :update_status
      end
    end
  end

  get '/my_bookings', to: 'bookings#my_bookings'
  get '/my_flats', to: 'flats#my_flats'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat

  validates :start_date, :end_date, presence: true
  validates :status, presence: true, inclusion: { in: ["pending", "confirmed", "declined"] }
  validate :start_date_before_end_date
  validate :no_overlap, on: :create
  validate :no_overlap_on_update, on: :update

  private

  def start_date_before_end_date
    if start_date >= end_date
      errors.add(:start_date, "must be before end date")
    end
  end

  def no_overlap
    if (Booking.where(flat_id: flat_id).where("(? <= end_date) and (? >= start_date)", self.start_date, self.end_date).where(status: "confirmed").any?)
      errors.add(:base, 'There is an overlapping booking')
    end
  end

  def no_overlap_on_update
    if self.status == "confirmed"
      if (Booking.where(flat_id: flat_id).where("(? <= end_date) and (? >= start_date)", self.start_date, self.end_date).where(status: "confirmed").any?)
        errors.add(:base, 'There is an overlapping booking')
      end
    end
  end
end

app/models/flat.rb
class Flat < ApplicationRecord
  geocoded_by :address
  belongs_to :user
  has_many :bookings, dependent: :destroy

  validates :name, :description, :address, :price_per_night, presence: true
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :flats, dependent: :destroy
  has_many :bookings, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @flat = Flat.find(params[:flat_id])
    @bookings_per_flat = @flat.bookings
  end

  def my_bookings
    @bookings_per_user = current_user.bookings
  end

  def create
    if !user_signed_in?
      flash[:error] = "You need to sign in to book a flat"
      redirect_to new_user_session_path
      return
    end
    
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new(booking_params)
    @booking.flat = @flat
    @booking.user = current_user
    @booking.status = "pending"
    @booking.total_price = @booking.flat.price_per_night * (@booking.end_date - @booking.start_date).to_i
    if @booking.save
      redirect_to flats_path
    else
      flash[:error] = @booking.errors.full_messages.join(", ")
      # TODO fix flash.now to use with render
      # render "flats/show"
      redirect_to flat_path(@flat)
    end 
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def update_status
    logger.debug "CEST ICIIIIIII"

    @booking = Booking.find(params[:id])
    logger.debug @booking
    @booking.update(status: params[:status])
    redirect_to flat_bookings_path(@booking.flat)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status, :total_price)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @flats = Flat.all
    if params[:query].present?
      @flats = @flats.where("name LIKE ? OR address LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%")
    end

    if params[:guest].present?
      @flats = @flats.where("guest >= ?", params[:guest])
    end

    if params[:min_price].present?
      @flats = @flats.where("price_per_night >= ?", params[:min_price])
    end

    if params[:max_price].present?
      @flats = @flats.where("price_per_night <= ?", params[:max_price])
    end

    if params[:sort].present?
      case params[:sort]
      when 'price_asc'
        @flats = @flats.order(price_per_night: :asc)
      when 'price_desc'
        @flats = @flats.order(price_per_night: :desc)
      when 'guests_asc'
        @flats = @flats.order(guest: :asc)
      when 'guests_desc'
        @flats = @flats.order(guest: :desc)
      end
    end


    # The `geocoded` scope filters only flats with coordinates
    @markers = @flats.geocoded.map do |flat|
        {
          lat: flat.latitude,
          lng: flat.longitude
        } 
    end 
    logger.debug @markers

    # This is to respond to the AJAX request
    respond_to do |format|
      # Follow regular flow of Rails if the request is HTML
      format.html 
      # This will render the partial `flats/list.html.erb` with the locals `flats` and `formats` as `html` if the request is JS (AJAX)
      format.text { render partial: 'flats/list', locals: { flats: @flats },  formats: :html }
    end

  end

  def my_flats
    @my_flats = current_user.flats    
  end

  def show
    @flat = Flat.find(params[:id])
    @booking = Booking.new
    @markers = [{
      lat: @flat.latitude,
      lng: @flat.longitude
    }]
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
      # TODO -> voir pourquoi les erreurs ne s'affichent pas
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :description, :price_per_night, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @flats = Flat.order(price_per_night: :desc).limit(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookings/index.html.erb
<h1>les bookings de cet appart</h1>

<% @bookings_per_flat.each do |booking| %>
  <% if(booking.status != "declined") %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= booking.start_date %></h5>
        <h6 class="card-subtitle mb-2 text-body-secondary"><%= booking.end_date %></h6>
        <p class="card-text"><%= booking.user.email %></p>
        <p class="card-text"><%= booking.status %></p>

        <%= button_to 'Confirmer',  update_status_flat_booking_path(booking.flat, booking, status: 'confirmed'), method: :patch %>
        <%= button_to 'Annuler',  update_status_flat_booking_path(booking.flat, booking, status: 'declined'), method: :patch %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/bookings/my_bookings.html.erb
<h1>Index bookings</h1>

<% @bookings_per_user.each do |booking| %>
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= booking.flat.name %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= booking.start_date %> | <%= booking.end_date %></h6>
      <p class="card-text"><%= booking.total_price %></p>
      <%= link_to "more details", flat_booking_path(booking.flat, booking)  %>
    </div>
  </div>
<% end %>

app/views/bookings/show.html.erb
<h1>show booking</h1>

app/views/flats/_list.html.erb
<div data-search-flat-target="list">
  <% if @flats.empty? %>
    <h2>Aucun Résultat</h2>
  <% else %>
  <div class="section-flats">
    <div class="flats-layout">
      <% @flats.each do |flat| %>
        <div >
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= flat.name %></h5>
              <h6 class="card-subtitle mb-2 text-body-secondary"><%= flat.price_per_night %></h6>
              <p class="card-text"><%= flat.description %></p>
              <p class="card-text"><%= pluralize(flat.guest, 'guest') %></p>
              <%= link_to "voir plus", flat_path(flat) %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
      <div class="flats-map" >
        <div style="height: 90vh; position: sticky; top: 20px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
  </div>
  <% end %>  
</div>

app/views/flats/index.html.erb
<div data-controller="search-flat">
  <div class="row justify-content-center">
    <div class="col-sm-8 my-3">
      <%= form_with url: flats_path, method: :get, html: { class: 'd-flex', data: { search_flat_target: 'form', action: 'submit->search-flat#update' } } do %>
        <%= text_field_tag :query,
              "",
              class: "form-control",
              placeholder: "Type a keyword",
              value: params[:query],
              data: { 
                search_flat_target: 'searchInput', 
              }
          %>

          <%= number_field_tag :guest,
              "",
              class: "form-control",
              placeholder: "guests",
              value: params[:guest],
              data: { 
                search_flat_target: 'searchGuest', 
              }
          %>
          <%# <div id="validationServerUsernameFeedback" class="invalid-feedback">
            Please choose a username.
          </div> %>
          <%= number_field_tag :min_price,
              "",
              class: "form-control",
              placeholder: "min-price",
              value: params[:min_price],
              data: { 
                search_flat_target: 'minPrice', 
              }
          %>
          <%= number_field_tag :max_price,
              "",
              class: "form-control",
              placeholder: "max-price",
              value: params[:max_price],
              data: { 
                search_flat_target: 'maxPrice', 
              }
          %>
        <%= submit_tag "Search", name: "", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

  <div>
   <%= form_tag flats_path, method: :get, data: { search_flat_target: 'sorter' } do %>
    <%= select_tag :filter_option,
        options_for_select([
          ['Tri par défaut', 'default'],
          ['prix croissant', 'price_asc'],
          ['prix décroissant', 'price_desc'],
          ['guests croissant', 'guests_asc'],
          ['guests décroissant', 'guests_desc']
        ]),
        class: "form-control",
        data: { 
          action: "change->search-flat#filter"
        }
    %>
    <% end %>
  </div>
  <%= render 'flats/list', flats: @flats %>
</div>

app/views/flats/my_flats.html.erb
<h1>my flats</h1>

<div class="d-flex justify-content-evenly">
  <% @my_flats.each do |flat| %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= flat.name %></h5>
        <h6 class="card-subtitle mb-2 text-body-secondary"><%= flat.price_per_night %></h6>
        <p class="card-text"><%= flat.description %></p>
        <%= link_to "voir plus", flat_path(flat) %>
        <%= link_to "bookings", flat_bookings_path(flat) %>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<h1>add a flat</h1>

<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price_per_night, as: :integer %>
  <%= f.input :guest, as: :integer %>
  <%= f.input :address %>

  <%= f.submit "Add a flat", class: "btn btn-primary" %>
<% end %>

app/views/flats/show.html.erb
<div data-controller="fetch-activities">
  <div class="flat-content-layout" >
    <div class="flat-content">
      <h1><%= @flat.name %> | <%= @flat.price_per_night %>€ par nuit</h1>
      <p><%= @flat.description %></p>
      <p data-fetch-activities-target="address"><%= @flat.address %></p>

      <div class="mt-5">
        <div style="width: 80%; height: 300px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>
    </div>

    <div class="flat-booking-form-wrapper">
      <% if flash[:error] %>
        <div class="alert alert-danger">
          <%= flash[:error] %>
        </div>
      <% end %>
      <%= simple_form_for [@flat, @booking] do |f| %>
        <%= f.input :start_date,
              as: :string,
              input_html: { class: "bg-white", data: { controller: "datepicker" } } %>
        <%= f.input :end_date,
                as: :string,
                input_html: { class: "bg-white", data: { controller: "datepicker" } } %>
        <%= f.submit "Ask for booking", class: "btn btn-primary w-100" %>
      <% end %>
    </div>
  </div>
  <div class="activities-layout" data-fetch-activities-target="activities">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>test</h1>

<div class="d-flex justify-content-evenly">
  <% @flats.each do |flat| %>
    <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= flat.name %></h5>
          <h6 class="card-subtitle mb-2 text-body-secondary"><%= flat.price_per_night %></h6>
          <p class="card-text"><%= flat.description %></p>
          <%= link_to "voir plus", flat_path(flat) %>
        </div>
      </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to "All Flats", flats_path, class: "nav-link" %>
          </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Add a flat", new_flat_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Flats", my_flats_path, class: "dropdown-item" %>
              <%= link_to "My Bookings", my_bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>